import { Link, useParams } from 'react-router-dom'
import { ScreenShell } from '../components/layout/ScreenShell'
import { ProjectCard } from '../components/content/ProjectCard'
import { projects } from '../data/projects'
import { skillGroups } from '../data/skills'
import { site, socials } from '../data/site'

export function ProjectsScreen() { return <ScreenShell title="Selected work" eyebrow="02 / portfolio"><p className="lede">Two projects, both live in public repositories. The first is a prompt evaluation and regression-testing framework; the second a machine-learning intrusion detection system with a Flask front-end. Each has a case file with the problem, the solution, and what the source reports.</p><div className="project-grid">{projects.map((project) => <ProjectCard project={project} key={project.slug} />)}</div></ScreenShell> }

export function ProjectDetailScreen() { const { slug } = useParams(); const project = projects.find((item) => item.slug === slug); if (!project) return <ScreenShell title="File not found" eyebrow="404"><p className="lede">That project record does not exist.</p><Link className="button-link" to="/projects">Return to projects</Link></ScreenShell>; return <ScreenShell title={project.name} eyebrow={`${project.category} / case file`}><div className="detail-grid"><section className="detail-lead"><div className="project-art large" aria-hidden="true"><span className="art-code">CASE</span><span className="art-shape" /></div><p className="lede">{project.summary}</p><p className="result-callout"><span>RESULT</span>{project.result}</p><a className="button-link" href={project.url} target="_blank" rel="noreferrer">View source / demo ↗</a></section><dl className="detail-facts"><div><dt>Problem</dt><dd>{project.problem}</dd></div><div><dt>Solution</dt><dd>{project.solution}</dd></div><div><dt>Contribution</dt><dd>{project.contribution}</dd></div><div><dt>Stack</dt><dd>{project.stack.join(' · ')}</dd></div></dl></div></ScreenShell> }

export function SkillsScreen() { return <ScreenShell title="The toolkit" eyebrow="03 / capabilities"><p className="lede">A living map of the practices, tools, and conversations that shape the work.</p><div className="skill-grid">{skillGroups.map((group) => <article className="skill-panel" key={group.title}><p className="eyebrow">{group.eyebrow}</p><h2>{group.title}</h2><ul>{group.skills.map((skill) => <li key={skill}>{skill}</li>)}</ul><p>{group.evidence}</p></article>)}</div></ScreenShell> }

export function AboutScreen() { return <ScreenShell title="Behind the mask" eyebrow="04 / profile"><div className="about-grid"><div><div className="portrait-fallback" aria-label="Original abstract portrait placeholder" role="img"><span>SS</span></div><p className="caption">Original abstract portrait placeholder</p></div><div className="about-copy"><p className="lede">{site.bio}</p><h2>Working signal</h2><ul className="profile-points">{site.aboutPoints.map((point) => <li key={point}>{point}</li>)}</ul></div></div></ScreenShell> }

export function ResumeScreen() { return <ScreenShell title="Credentials" eyebrow="05 / resume"><div className="resume-panel"><div className="resume-stamp">CV</div><div><p className="lede">Background, toolkit, and shipped work, all in one place. Each group below is the same verified data that lives on the Skills and Projects screens.</p><div className="resume-groups">{skillGroups.map((group) => <div className="resume-group" key={group.title}><p className="eyebrow">{group.eyebrow}</p><h2>{group.title}</h2><ul>{group.skills.map((skill) => <li key={skill}>{skill}</li>)}</ul></div>)}</div><a className="button-link resume-cta" href={site.email}>Request the full CV ↗</a></div></div></ScreenShell> }

export function ContactScreen() { return <ScreenShell title="Open a channel" eyebrow="06 / contact"><div className="contact-panel"><p className="lede">Have a thoughtful problem, a prototype to sharpen, or a team building something useful? The fastest route is email.</p><a className="contact-email" href={site.email}>{site.email.replace('mailto:', '')} ↗</a></div></ScreenShell> }

export function SocialsScreen() { return <ScreenShell title="Further signal" eyebrow="07 / socials"><div className="social-list">{socials.map((social, index) => <a className="social-row" href={social.href} target={social.href.startsWith('http') ? '_blank' : undefined} rel={social.href.startsWith('http') ? 'noreferrer' : undefined} key={social.label}><span>0{index + 1}</span><strong>{social.label}</strong><small>{social.note}</small><b>↗</b></a>)}</div></ScreenShell> }

export function NotFoundScreen() { return <ScreenShell title="Unknown route" eyebrow="404"><p className="lede">The command center could not find that destination.</p><Link className="button-link" to="/">Return home</Link></ScreenShell> }
